# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

      - job_name: "blackbox"
        metrics_path: "/probe"
        params:
          module: [http_2xx]
        scrape_interval: 60s
        static_configs:
        - targets:
          - "https://localhost:3000"
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: host.docker.internal:9115
      - job_name: "blackbox_exporter"
        static_configs:
        - targets: ['127.0.0.1:9115']

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:8081/dataCollectionRules/dcr-6b75836ff8d6428c8a9da60e6a292bb5/streams/Microsoft-PrometheusMetrics/api/v1/write?api-version=2023-04-24
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
